image:
  file: .gitpod.Dockerfile
tasks:
    - name: WIKI
      init: curl https://raw.githubusercontent.com/crystaluniverse/crystaltools/development/scripts/ct_init | bash
      command: source /workspace/crystaltools/env && sudo /etc/init.d/redis-server start && clear && ct_help
    - name: Build
      openMode: split-right
      init: curl https://raw.githubusercontent.com/crystaluniverse/crystaltools/development/scripts/ct_init | bash
      command: source /workspace/crystaltools/env && ct_build && reset && ct_help

ports:
  - port: 9998
    onOpen: open-browser
  - port: 6379
    onOpen: ignore
vscode:
  extensions:
    - vlanguage.vscode-vlang
    - telesoho.vscode-markdown-paste-image
    - yzhang.markdown-all-in-one
    - shd101wyy.markdown-preview-enhanced
    - bierner.markdown-mermaid
    - darkriszty.markdown-table-prettify
    - bpruitt-goddard.mermaid-markdown-syntax-highlighting
    - shuworks.vscode-table-formatter
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
